### PR TITLE
Enabled the possibility to use lager as backend

### PR DESCRIPTION
**Pull request by windkit**
Redefine the macros
and keep the message records so leo_logger can still be accessible

### CODE REVIEW

**Comment by yosukehara** [comment]
@windkit I've reviewed your PR. I'd like to ask you to modify it as below:

- Able to switch the current logging feature or the new feature which depends on `erlang/lager` by a leo_logger's configuration.
- Merge `include/lager_logger.hrl` into `include/leo_logger.hrl`.

This is a measure for the first phase. After releasing v1.3.5, we need to consider the implementation of an hourly log.

**Comment by windkit** [comment]
@yosukehara I have updated repo and is testing with leo_gateway

**Comment by windkit** [comment]
GW PR: https://github.com/leo-project/leofs/pull/749

**Comment by mocchira** [comment]
@windkit @yosukehara I have still not checked in detail however I'm sure that the current implementation to check which backends is active by a case clause with **application:get_env** each time when calling log functions is too expensive in terms of computation cost and exclusive locks are involved behind the scene so instead I would recommend to use the dynamic dispatch approach with erlang:apply that have used at the other places.

**Comment by yosukehara** [comment]
@mocchira I've asked @windkit to modify this PR using `application:get_env` on the first step. I'll consider how to not use `application:get_env`. I've briefly checked dispatching a logger, which is implemented to [leo_logger_server](https://github.com/leo-project/leo_logger/blob/develop/src/leo_logger_server.erl).

**Comment by yosukehara** [comment]
@windkit I recommend you modify the code as below:
- Modify [leo_logger_server:start_link/4](https://github.com/leo-project/leo_logger/blob/develop/src/leo_logger_server.erl#L55)
    - Plus an argument which is **the return value of `application:get_env(leo_logger, log_backend)`**
    - Need to modify [#logger_state{}](https://github.com/leo-project/leo_logger/blob/develop/include/leo_logger.hrl#L62)  _(+ log_backend)_
- Then Modify [leo_logger_server:append_sub/2](https://github.com/leo-project/leo_logger/blob/develop/src/leo_logger_server.erl#L274)

**Comment by yosukehara** [comment]
@mocchira This improvement is for the 1st phase. In the 2nd phase, we're planning to fix overload problem with the hourly log as well.

**Comment by windkit** [comment]
I would first close this PR, and we will have discussion on this again.

**Pull request closed without merging**
